project:
  type: website
  output-dir: docs

website:
  title: "fastroads"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fast-roads.qmd
        text: Fast Roads
      - href: about-us.qmd
        text: About Us
      - href: blog.qmd
        text: Blog
      - href: contact-page.qmd
        text: Contact Us
      - href: data.qmd
        text: Data

bibliography: references.bib

format:
  html:
    theme: lux
    css: styles.css
    toc: true



